# Numerical Computing with NumPy

## Arrays with Python Lists

In [1]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [2]:
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [3]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [4]:
m[1][0]

0.5

In [5]:
v1 = [0.5, 1.5]
v2 = [1, 2]
m = [v1, v2]
c = [m, m]
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [6]:
c[1][1][0]

1

In [7]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [8]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [9]:
from copy import deepcopy
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 * [deepcopy(v), ]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [10]:
v[0] = 'Python'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

## Regular NumPy Arrays

### The Basics

In [11]:
import numpy as np

In [12]:
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [13]:
type(a)

numpy.ndarray

In [14]:
a = np.array(['a', 'b', 'c'])
a

array(['a', 'b', 'c'], dtype='<U1')

In [15]:
a = np.arange(2, 20, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
a = np.arange(8, dtype=np.float64)
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [17]:
a[5:]

array([5., 6., 7.])

In [18]:
a[:2]

array([0., 1.])

In [19]:
a.sum()

28.0

In [20]:
a.std()

2.29128784747792

In [21]:
a.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [22]:
l = [0., 0.5, 1.5, 3., 5.]
2 * l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [23]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [24]:
2 * a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [25]:
a ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [26]:
2 ** a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [27]:
a ** a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [28]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [29]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [30]:
np.sqrt(2.5)

1.5811388300841898

In [31]:
import math
math.sqrt(2.5)

In [32]:
%timeit np.sqrt(2.5)

923 ns ± 102 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [33]:
%timeit math.sqrt(2.5)

122 ns ± 31.3 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


### Multiple Dimensions

In [34]:
b = np.array([a, a * 2])
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [35]:
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [36]:
b[0, 2]

2.0

In [37]:
b[:, 1]

array([1., 2.])

In [38]:
b.sum()

84.0

In [39]:
b.sum(axis=0)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [40]:
b.sum(axis=1)

array([28., 56.])

In [41]:
c = np.zeros((2, 3), dtype='i', order='C')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [42]:
c = np.ones((2, 3, 4), dtype='i', order='C')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [43]:
d = np.zeros_like(c, dtype='f16', order='C')
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float128)

In [44]:
d = np.ones_like(c, dtype='f16', order='C')
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float128)

### Speed Comparison

In [45]:
import random
I = 5000

In [46]:
%time mat = [[random.gauss(0, 1) for j in range(I)] \
             for i in range(I)]

CPU times: user 18 s, sys: 1.7 s, total: 19.7 s
Wall time: 19.8 s


In [47]:
%time sum([sum(l) for l in mat])

CPU times: user 245 ms, sys: 0 ns, total: 245 ms
Wall time: 246 ms


-3659.339754012995

In [48]:
%time mat = np.random.standard_normal((I, I))

CPU times: user 748 ms, sys: 113 ms, total: 861 ms
Wall time: 857 ms


In [49]:
%time mat.sum()

CPU times: user 20.6 ms, sys: 0 ns, total: 20.6 ms
Wall time: 20.9 ms


-11736.87592817509

### Structured Arrays

In [50]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'),
               ('Height', 'f'), ('Children/Pets', 'i4', 2)])
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [51]:
s = np.array([('Smith', 45, 1.83, (0, 1)),
              ('Jones', 53, 1.72, (2, 2))], dtype=dt)
s

array([(b'Smith', 45, 1.83, [0, 1]), (b'Jones', 53, 1.72, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [52]:
s['Name']

array([b'Smith', b'Jones'], dtype='|S10')

In [53]:
s['Height'].mean()

1.7750001

In [54]:
s[1]['Age']

53

## Vectorization of Code

In [55]:
np.random.seed(100)
r = np.arange(12).reshape((4, 3))
s = np.arange(12).reshape((4, 3)) * 0.5

In [56]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [58]:
r + s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [60]:
r + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [61]:
2 * r

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [62]:
2 * r + 3

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [63]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [64]:
r.shape

(4, 3)

In [65]:
s = np.arange(0, 12, 4)
s

array([0, 4, 8])

In [66]:
r + s

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [67]:
s = np.arange(0, 12, 3)
s

array([0, 3, 6, 9])

In [68]:
# causes intentional error
r + s

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [69]:
r.transpose() + s

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [70]:
sr = s.reshape(-1, 1)
sr

array([[0],
       [3],
       [6],
       [9]])

In [71]:
sr.shape

(4, 1)

In [72]:
r + s.reshape(-1, 1)

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [73]:
def f(x):
    return 3 * x + 5

In [74]:
f(0.5)

6.5

In [75]:
f(r)

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])